$baseDir = "e:\000VSCODE PROJECT MULAI DARI DESEMBER 2025\CV KERJA\my-professional-resumes"
$masterCvDir = Join-Path $baseDir "Master-CVs"
$outputDir = Join-Path $baseDir "Premium_Career_Suite"

if (!(Test-Path $outputDir)) { New-Item -ItemType Directory -Path $outputDir }

$categories = @(
    "01-Web3-Solana", "02-Eth-Base", "03-Mobile-Flutter", "04-AI-Automation",
    "05-GameFi-Degen", "06-Community-Growth", "07-Web3-Strategy", "08-Fintech-Payments"
)

$CSS = @"
body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; line-height: 1.5; color: #1a1a1a; max-width: 850px; margin: 0 auto; padding: 60px; background-color: #fcfcfc; box-shadow: 0 0 50px rgba(0,0,0,0.05); }
h1 { color: #000; border-bottom: 3px solid #000; padding-bottom: 10px; margin-top: 40px; font-size: 28pt; letter-spacing: -1px; }
h2 { color: #2c3e50; border-bottom: 1px solid #ddd; padding-bottom: 5px; margin-top: 35px; font-size: 20pt; }
h3 { color: #34495e; border-left: 5px solid #000; padding-left: 15px; margin-top: 25px; font-size: 16pt; }
p { margin: 12px 0; font-size: 12pt; }
ul { margin: 12px 0; padding-left: 25px; }
li { margin: 6px 0; font-size: 12pt; }
strong { color: #000; font-weight: bold; }
a { color: #0078d4; text-decoration: none; border-bottom: 1px solid transparent; transition: border-bottom 0.2s; }
a:hover { border-bottom: 1px solid #0078d4; }
hr { border: 0; border-top: 2px solid #eee; margin: 40px 0; }
.meta { font-style: italic; color: #666; font-size: 10pt; text-align: right; }
@media print {
    body { padding: 0; box-shadow: none; background: #fff; }
    .no-print { display: none; }
}
"@

foreach ($cat in $categories) {
    $catPath = Join-Path $masterCvDir $cat
    if (!(Test-Path $catPath)) { continue }
    
    $files = Get-ChildItem -Path $catPath -Filter "*.md"
    foreach ($file in $files) {
        $md = Get-Content -Path $file.FullName -Raw
        
        # Simple HTML conversion
        $body = $md -replace '^# (.*)$', '<h1>$1</h1>' `
                    -replace '^## (.*)$', '<h2>$1</h2>' `
                    -replace '^### (.*)$', '<h3>$1</h3>' `
                    -replace '\*\*(.*?)\*\*', '<strong>$1</strong>' `
                    -replace '^- (.*)$', '<li>$1</li>' `
                    -replace '\[(.*?)\]\((.*?)\)', '<a href="$2">$1</a>'
        
        $body = $body -replace '<li>(.*?)</li>(\r?\n<li>.*?</li>)*', '<ul>$&</ul>'
        $body = $body -replace '(\r?\n){2,}', '<p>'
        
        $htmlFile = Join-Path $outputDir "$($file.BaseName)_Premium.html"
        
        @"
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>$($file.BaseName) | Career Suite</title>
    <style>$CSS</style>
</head>
<body>
    <div class="no-print" style="margin-bottom: 40px; text-align: center; background: #000; color: #fff; padding: 15px; border-radius: 8px; font-weight: bold;">
        💎 PREMIUM CAREER SUITE | Open this file and press Ctrl+P (Save as PDF) for instant deployment.
    </div>
    $body
    <div class="meta">Generated by Antigravity AI for @nayrbryanGaming | 2026</div>
</body>
</html>
"@ | Out-File -FilePath $htmlFile -Encoding utf8
    }
}

Write-Host "✅ 16 Premium HTML Assets Created in Premium_Career_Suite"
